variables:
  APP_NAME: anselme
  REVIEW_APP_NAME: anselme-${CI_COMMIT_REF_NAME}
  REVIEW_API_ENDPOINT: ip10-0-1-4-cm07alq2mkn0ljtam6a0-1993.direct.docker.labs.eazytraining.fr
  REVIEW_APP_ENDPOINT: ip10-0-1-4-cm07alq2mkn0ljtam6a0-80.direct.docker.labs.eazytraining.fr
  STG_API_ENDPOINT: ip10-0-1-5-cm07alq2mkn0ljtam6a0-1993.direct.docker.labs.eazytraining.fr
  STG_APP_ENDPOINT: ip10-0-1-5-cm07alq2mkn0ljtam6a0-80.direct.docker.labs.eazytraining.fr
  PROD_API_ENDPOINT: ip10-0-1-6-cm07alq2mkn0ljtam6a0-1993.direct.docker.labs.eazytraining.fr
  PROD_APP_ENDPOINT: ip10-0-1-6-cm07alq2mkn0ljtam6a0-80.direct.docker.labs.eazytraining.fr
  INTERNAL_PORT: 5000
  EXTERNAL_PORT: 80
  CONTAINER_IMAGE: ${IMAGE_NAME}:${CI_COMMIT_REF_NAME}


image: docker:latest
services:
  - name: docker:dind
    alias: docker


stages:
  - build
  - Test acceptation
  - Release image
  - Deploy review
  - Stop review
  - Deploy staging
  - Test staging  
  - Deploy prod
  - Test prod

.test_template: &test
  image: alpine
  only:
    - master
  script:
    - apk --no-cache add curl
    - curl "https://$DOMAIN" | grep "Hello world!"  

docker-build:
  # Use the official docker image.
  stage: build
  script:
    - docker build -t  alpinehelloworld .
    - docker save alpinehelloworld > alpinehelloworld.tar
  artifacts:
    paths:
      - alpinehelloworld.tar    


test acceptation:
  # Official docker image.
  stage: Test acceptation
  script:
    - docker load < alpinehelloworld.tar
    - docker run -d -p 80:5000 -e PORT=5000 --name webapp alpinehelloworld
    - sleep 5
    - apk --no-cache add curl
    - curl "http://docker" | grep  "Hello world!"

release image:
  stage: Release image
  script:
    - docker load < alpinehelloworld.tar
    - docker tag alpinehelloworld "${IMAGE_NAME}:${CI_COMMIT_REF_NAME}"
    - docker tag alpinehelloworld "${IMAGE_NAME}:${CI_COMMIT_SHORT_SHA}"
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker push "${IMAGE_NAME}:${CI_COMMIT_REF_NAME}"
    - docker push "${IMAGE_NAME}:${CI_COMMIT_SHORT_SHA}"

deploy staging:
  stage: Deploy staging
  environment:
    name: staging
    url: http://${STG_APP_ENDPOINT}
  only:
    - master    
  script:
    - apk --no-cache add curl
    - 'curl -X POST http://${STG_API_ENDPOINT}/staging -H "Content-Type: application/json" -d "{\"your_name\":\"${APP_NAME}\",\"container_image\":\"${CONTAINER_IMAGE}\", \"external_port\":\"${EXTERNAL_PORT}\", \"internal_port\":\"${INTERNAL_PORT}\"}"'

deploy prod:
  stage: Deploy prod
  environment:
    name: prod
    url: http://${PROD_APP_ENDPOINT}
  only:
    - master
  script:
    - apk --no-cache add curl
    - 'curl -X POST http://${PROD_API_ENDPOINT}/prod -H "Content-Type: application/json" -d "{\"your_name\":\"${APP_NAME}\",\"container_image\":\"${CONTAINER_IMAGE}\", \"external_port\":\"${EXTERNAL_PORT}\", \"internal_port\":\"${INTERNAL_PORT}\"}"'


deploy review:
  stage: Deploy review
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: http://${REVIEW_APP_ENDPOINT}
    on_stop: stop review
  only:
    - merge_requests
  variables:
    APP_NAME: ${REVIEW_APP_NAME}
  script:
    - apk --no-cache add curl
    - echo $APP_NAME
    - 'curl -X POST http://${REVIEW_API_ENDPOINT}/review -H "Content-Type: application/json" -d "{\"your_name\":\"${APP_NAME}\",\"container_image\":\"${CONTAINER_IMAGE}\", \"external_port\":\"${EXTERNAL_PORT}\", \"internal_port\":\"${INTERNAL_PORT}\"}"'

stop review:
  stage: Stop review
  variables:
    GIT_STRATEGY: none
    APP_NAME: ${REVIEW_APP_NAME}
  environment:
    name: review/$CI_COMMIT_REF_NAME
    action: stop
  only:
    - merge_requests
  when: manual  
  script:
    - apk --no-cache add curl
    - 'curl -X DELETE http://${REVIEW_API_ENDPOINT}/review -H "Content-Type: application/json" -d "{\"your_name\":\"${APP_NAME}\"}"'

test staging:
  <<: *test
  stage: Test staging
  variables:
    DOMAIN: ${STG_APP_ENDPOINT}


test prod:
  <<: *test
  stage: Test prod 
  variables:
    DOMAIN: ${PROD_APP_ENDPOINT}